In [29]:
import numpy
import requests, sys, os
from IPython.display import Image, display
from YandexMap import *


# Создание карты с соответствующими параметрами.
def load_map(mp, name: str, mp_res=None):
    #ll - центр (автомат)
    #z(zoom) - масштабирование (автомат)
    #size - разрешение изображения
    #bbox - границы отображения
    second_line = ""
    if mp_res is not None:
        second_line = f"~c:0xFFA500FF,w:6,bw:3,{mp_res.line_key()}"

    map_request = "http://static-maps.yandex.ru/1.x/?&size={sz}&l={type}&pl=w:6,bw:3,{coords}{second_coords}". \
        format(type=mp.type,
               sz=mp.size_key(),
               coords=mp.line_key(),
               bbox=mp.bbox_key(),
               second_coords=second_line)

    response = requests.get(map_request)
    if not response:
        print(f"Ошибка с файлом {name}")
        print("Ошибка выполнения запроса:")
        print(map_request)
        print("Http статус:", response.status_code, "(", response.reason, ")")
        #sys.exit(1)

    # Запись полученного изображения в файл.
    map_file = f"results/{name}.png"
    try:
        with open(map_file, "wb") as file:
            file.write(response.content)
    except IOError as ex:
        print("Ошибка записи временного файла:", ex)
        sys.exit(2)
    return map_file


def find_type_file(data: list):
    cnt_strings = 0
    for i in data:
        if i != '':
            cnt_strings += 1
        else:
            break
    return cnt_strings


def main():
    # if len(args) != 2:
    #     sys.exit(2)
    #
    # filename = args[1]
    isExist = os.path.exists("results")
    if not isExist:
        os.makedirs("results")

    with open(f"data.txt") as file:
        # Убираем пустые строки
        dataset = file.read().split('\n')
        cnt_strings = find_type_file(dataset)
        dataset = list(filter(None, dataset))

    if cnt_strings == 2:
        #  Проходимся по каждому тайфуну
        for name, coords in zip(dataset[::2], dataset[1::2]):
            data = numpy.array(list(coords.strip().split(',')), dtype=float).reshape(-1, 2)
            print(data)
            mp = MapParams(data)
            load_map(mp, name)

    if cnt_strings == 3:
        for name, orig, result in zip(dataset[::3], dataset[1::3], dataset[2::3]):
            orig_data = numpy.array(list(orig.strip().split(',')), dtype=float).reshape(-1, 2)
            result_data = numpy.array(list(result.strip().split(',')), dtype=float).reshape(-1, 2)

            orig_mp = MapParams(orig_data)
            res_mp = MapParams(result_data)
            load_map(orig_mp, name, res_mp)


if __name__ == "__main__":
    main()

[[ 18.8 -85.8]
 [ 21.4 -84.8]
 [ 22.3 -84.2]
 [ 23.3 -83.9]
 [ 24.5 -83.6]
 [ 25.1 -83.3]
 [ 25.8 -82.9]
 [ 26.9 -82.1]
 [ 28.1 -80.9]]
[[ 20.  -87. ]
 [ 20.  -86.2]
 [ 23.8 -85.6]
 [ 24.8 -85.7]
 [ 26.  -85.7]
 [ 27.2 -85.7]
 [ 28.5 -85.7]
 [ 29.6 -85.6]
 [ 31.4 -84.7]
 [ 32.9 -82.8]
 [ 33.5 -81.7]]
[[ 21.7 -87.1]
 [ 22.2 -86.5]
 [ 22.6 -85.8]
 [ 22.8 -85. ]
 [ 23.2 -84.2]
 [ 24.  -83.6]
 [ 24.8 -83.4]
 [ 24.9 -84.1]
 [ 24.9 -84.8]
 [ 25.  -84.2]
 [ 25.1 -84.1]
 [ 25.2 -84. ]]
[[ 32.  -77.5]
 [ 32.8 -76.2]
 [ 34.  -75.2]
 [ 35.2 -74.6]
 [ 37.  -73.5]
 [ 38.7 -72.4]
 [ 40.  -70.8]
 [ 41.5 -69. ]
 [ 43.  -67.5]]
[[ 21.7 -83.6]
 [ 21.6 -84.3]
 [ 21.6 -85.2]
 [ 21.5 -85.6]
 [ 22.  -86.1]
 [ 22.5 -86.4]
 [ 23.  -86.7]
 [ 23.7 -87.1]
 [ 24.4 -87.5]
 [ 25.5 -87.5]
 [ 26.5 -86.9]
 [ 27.7 -86.8]
 [ 28.8 -86.8]
 [ 29.9 -86.7]
 [ 30.4 -86.5]
 [ 30.7 -86.3]
 [ 31.2 -86.1]
 [ 31.7 -85.9]
 [ 32.3 -85.5]
 [ 32.7 -85.2]
 [ 33.  -85. ]
 [ 33.2 -84.9]
 [ 33.3 -84.8]
 [ 33.5 -84.6]]
[[ 20.  -85. ]
 [ 21